const SUPABASE_URL='https://smzywlljyhcnymukakkc.supabase.co';
const SUPABASE_KEY='sb_publishable_tkN-c_D3CJBaNe9PZFc5Yw_WJ6VcuQx';
let adminSession=null;
const headers={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`};
const links=[...document.querySelectorAll('.nav a')],sections=links.map(link=>document.querySelector(link.getAttribute('href'))).filter(Boolean);
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)links.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#${entry.target.id}`));}),{rootMargin:'-35% 0px -55% 0px'});sections.forEach(section=>observer.observe(section));
const form=document.querySelector('#mod-form'),list=document.querySelector('#mod-list'),message=document.querySelector('#form-message'),count=document.querySelector('.stats strong');
const safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[char]);
function addCard(mod){const card=document.createElement('article'),download=mod.file_url||mod.download_url;card.className='mod-card user-mod';card.dataset.id=mod.id;card.dataset.fileUrl=mod.file_url||'';const target=download?download+(download.includes('?')?'&':'?')+'download='+encodeURIComponent(mod.file_name||'mod-file'):'';card.innerHTML=`<div class="mod-icon">${safe(mod.name.slice(0,2).toUpperCase())}</div><div class="mod-info"><div class="mod-title"><h3>${safe(mod.name)}</h3><span class="version">v${safe(mod.version)}</span></div><p>${safe(mod.description)}</p><div class="tag-row"><span>Community</span><span>${safe(mod.file_name||'Download link')}</span></div></div>${target?`<a class="button primary download-button" download href="${safe(target)}" target="_blank" rel="noreferrer">Download ↗</a>`:''}`;list.append(card);if(target){const button=card.querySelector('.download-button'),downloadCount=Number(mod.download_count||0);button.insertAdjacentHTML('beforeend',` <span class="download-count">(${downloadCount})</span>`);button.addEventListener('click',()=>{fetch(`${SUPABASE_URL}/rest/v1/rpc/increment_mod_download`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({mod_id:mod.id})}).catch(()=>{})})}}
async function loadMods(){list.innerHTML='';const response=await fetch(`${SUPABASE_URL}/rest/v1/mods?select=*&published=eq.true&order=created_at.desc`,{headers});if(!response.ok)throw new Error('Could not load mods.');const mods=await response.json();if(count)count.textContent=mods.length;mods.forEach(addCard)}
loadMods().catch(()=>{message.textContent='The mod database is not set up yet.';});
const refresh=document.createElement('button');refresh.className='refresh-button';refresh.type='button';refresh.style.cssText='display:inline-flex;align-items:center;gap:10px;margin:0 0 28px;padding:12px 18px;border:1px solid #3d7cff;background:#3d7cff;color:#fff;font:600 14px DM Mono,monospace;cursor:pointer;transition:background .2s,border-color .2s';refresh.onmouseenter=()=>{refresh.style.background='#5a8cff';refresh.style.borderColor='#5a8cff'};refresh.onmouseleave=()=>{refresh.style.background='#3d7cff';refresh.style.borderColor='#3d7cff'};refresh.textContent='↻ Refresh mods';refresh.onclick=loadMods;document.querySelector('#mods').prepend(refresh);
form.addEventListener('submit',async event=>{event.preventDefault();const formData=new FormData(form),file=form.elements.file.files[0],mod={name:formData.get('name'),version:formData.get('version'),description:formData.get('description'),download_url:formData.get('url')||null,file_url:null,file_name:null,published:false},button=form.querySelector('button[type="submit"]');if(!mod.download_url&&!file){message.textContent='Add a download URL or choose a mod file first.';return}button.disabled=true;message.textContent='Submitting for admin review…';try{if(file){if(file.size>50*1024*1024)throw new Error('File is too large. Use a file smaller than 50 MB.');const path=`${crypto.randomUUID()}-${file.name}`,upload=await fetch(`${SUPABASE_URL}/storage/v1/object/mods/${encodeURIComponent(path)}`,{method:'POST',headers:{...headers,'Content-Type':file.type||'application/octet-stream'},body:file});if(!upload.ok){let detail='';try{detail=(await upload.json()).message||''}catch{}throw new Error(detail||`File upload failed (${upload.status}).`)}mod.file_url=`${SUPABASE_URL}/storage/v1/object/public/mods/${encodeURIComponent(path)}`;mod.file_name=file.name}const response=await fetch(`${SUPABASE_URL}/rest/v1/mods`,{method:'POST',headers:{...headers,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(mod)});if(!response.ok)throw new Error('Database insert failed.');form.reset();message.textContent='Submitted. Waiting for admin approval.';if(adminSession)loadPending()}catch(error){message.textContent=error.message}finally{button.disabled=false}});
let adminNav=document.querySelector('#admin-nav'),adminSection=document.querySelector('#admin'),admin=document.querySelector('#admin-login'),review=document.querySelector('#admin-review');if(!adminNav){adminNav=document.createElement('a');adminNav.id='admin-nav';adminNav.href='#admin';adminNav.textContent='Admin';adminNav.hidden=true;document.querySelector('.nav').append(adminNav)}if(!adminSection){adminSection=document.createElement('section');adminSection.id='admin';adminSection.className='submit-section section-shell';adminSection.hidden=true;adminSection.innerHTML='<h2>Admin review.</h2><p>Only logged-in admins can review and publish submitted mods.</p>';document.querySelector('main').append(adminSection);admin=document.createElement('form');admin.id='admin-login';admin.innerHTML='<input name="email" type="email" placeholder="Admin email" required><input name="password" type="password" placeholder="Password" required><button type="submit">Log in</button><span id="admin-message"></span>';adminSection.append(admin);review=document.createElement('div');review.id='admin-review';review.innerHTML='<h3>Pending mods</h3><div id="pending-mods">Log in to review submissions.</div>';adminSection.append(review)}
async function loadPending(){const box=review.querySelector('#pending-mods');box.textContent='Loading pending mods…';const response=await fetch(`${SUPABASE_URL}/rest/v1/mods?select=*&published=eq.false&order=created_at.desc`,{headers});if(!response.ok){box.textContent='Could not load pending mods.';return}const mods=await response.json();box.innerHTML=mods.length?'':'No pending mods.';mods.forEach(mod=>{const row=document.createElement('div');row.textContent=`${mod.name} — v${mod.version}`;const approve=document.createElement('button');approve.textContent='Publish';approve.onclick=async()=>{const result=await fetch(`${SUPABASE_URL}/rest/v1/mods?id=eq.${mod.id}`,{method:'PATCH',headers:{...headers,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({published:true})});if(result.ok){row.remove();loadMods()}};row.append(' ',approve);box.append(row)})}
admin.addEventListener('submit',async event=>{event.preventDefault();const note=admin.querySelector('#admin-message'),data=new FormData(admin);note.textContent='Logging in…';const response=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email:data.get('email'),password:data.get('password')})});if(!response.ok){note.textContent='Login failed.';return}adminSession=await response.json();headers.Authorization='Bearer '+adminSession.access_token;adminNav.hidden=false;adminSection.hidden=false;note.textContent='Admin logged in.';loadPending();loadMods();location.hash='admin'});
function addDelete(card){if(card.querySelector('.admin-delete'))return;const button=document.createElement('button');button.className='admin-delete';button.textContent='Delete';button.onclick=()=>deleteMod(card);card.append(button)}
async function deleteMod(card){if(!adminSession)return;const fileUrl=card.dataset.fileUrl,marker='/storage/v1/object/public/mods/';if(fileUrl.includes(marker)){const path=decodeURIComponent(fileUrl.split(marker)[1]);await fetch(`${SUPABASE_URL}/storage/v1/object/mods/${encodeURIComponent(path)}`,{method:'DELETE',headers})}const response=await fetch(`${SUPABASE_URL}/rest/v1/mods?id=eq.${encodeURIComponent(card.dataset.id)}`,{method:'DELETE',headers:{...headers,Prefer:'return=minimal'}});if(response.ok)card.remove()}
